### ISSUE TITLE
1.1.0 update

### ISSUE THREAD

**Issue by tipa** [rf43/FlexboxLayout.Droid.Bindings#1]
Any chance updating the bindings to v1.1.0? Thanks!

**Comment by rf43** [comment]
Thank you for letting me know that there is a 1.1.0 update!

I will work on getting it updated this weekend and let you know when I do.

**Comment by rf43** [comment]
@tipa I have updated it to 1.1.0 and added a link to the readme to directly download the nuget package. Let me know if you run into any issues and again, thank you for calling attention to this 😀

**Comment by tipa** [comment]
Thank you! Do you also plan to publish the package on Nuget.org?
https://www.nuget.org/packages/FlexboxLayout.Droid.Bindings

**Comment by rf43** [comment]
@tipa you rock!!! Thanks for pointing that out.

It is currently validating but here it is https://www.nuget.org/packages/FlexboxLayout.Droid.Bindings/1.1.0

**Comment by tipa** [comment]
Sorry to bug you again, but it seems like the `FlexboxLayoutManager` class isnt available in the 1.1.0 bindings any more :(

**Comment by rf43** [comment]
No worries :D

I checked and it does def seem that it is missing, which is odd because all the other stuff seems to be there just fine.

I have created a new issue to track this while I dig into it and see what the deal is. #3
