### ISSUE TITLE
Binding seems to be missing FlexboxLayoutManager

### ISSUE THREAD

**Issue by rf43** [rf43/FlexboxLayout.Droid.Bindings#3]
FlexboxLayoutManager seems to be missing in the latest update (v1.1.0)

**Comment by rf43** [comment]
It seems that Xamarin isn't ready for AndroidX yet. Therefore, v1.1.0 will not work until https://github.com/xamarin/AndroidSupportComponents is updated and useable so I can rebuild the nuget package.

**Comment by tipa** [comment]
I see. Thanks for looking into it!

**Comment by rf43** [comment]
Fixed and implemented in [release 1.1.0.1](https://github.com/rf43/FlexboxLayout.Droid.Bindings/releases/tag/1.1.0.1)

cc: @tipa
